easy_admin:
   site_name: 'NosAmisLesOiseaux'
   design:
      form_theme: 'horizontal'
      assets:
          js:
            - 'https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=zfywjcekks6ajywpq2nnrrms2h311dpnzudvvkal0bp06ep0'
            - '/assets/js/easy_admin.js'
   entities:
       Users:
            class: App\Entity\Users
            list:
              fields:
                - { property: 'id', label: 'users.id' }
                - { property: 'name', label: 'users.name' }
                - { property: 'firstname', label: 'users.firstname' }
                - { property: 'username', label: 'users.username' }
                - { property: 'mail', label: 'users.mail' }
                - { property: 'password', label: 'users.password' }
                - { property: 'newsletter', label: 'users.newsletter' }
                - { property: 'is_active', label: 'users.actif' }
                - { property: 'role', label: 'users.role' }
       Article:
            class: App\Entity\Article
            new:
              fields:
                - { property: 'title', label: 'article.title' }
                - { property: 'content', type: 'textarea', label: 'article.content' }
                - { property: 'imageFile', type: 'vich_image' }

            list:
              fields:
                - id
                - { property: 'title', label: 'article.title' }
                - { property: 'content', label: 'article.content' }
            edit:
              fields:
                - { property: 'title', label: 'article.title' }
                - { property: 'content', type: 'textarea', label: 'article.content' }
                - { property: 'imageFile', type: 'vich_image' }
       Comments:
            class: App\Entity\Comments
            list:
              fields:
                - { property: 'id', label: 'comments.id' }
                - { property: 'content', label: 'comments.content' }
                - { property: 'article_id', label: 'comments.article_id' }
       Birds:
            class: App\Entity\Birds
framework:
  translator: { fallbacks: [ "fr" ] }
  templating:
      engines: ['twig']

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\Entity\Users
    from_email:
        address: "contact@nos-amis-les-oiseaux.fr"
        sender_name: "contact@nos-amis-les-oiseaux.fr"


