easy_admin:
   site_name: 'NosAmisLesOiseaux'
   design:
      form_theme: 'horizontal'
      assets:
          js:
            - 'https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=zfywjcekks6ajywpq2nnrrms2h311dpnzudvvkal0bp06ep0'
            - '/assets/js/test.js'
   entities:
       Users:
            class: App\Entity\Users
            list:
              fields:
                - { property: 'id', label: 'users.id' }
                - { property: 'name', label: 'users.name' }
                - { property: 'firstname', label: 'users.firstname' }
                - { property: 'username', label: 'users.username' }
                - { property: 'mail', label: 'users.mail' }
                - { property: 'password', label: 'users.password' }
                - { property: 'newsletter', label: 'users.newsletter' }
                - { property: 'is_active', label: 'users.actif' }
                - { property: 'role', label: 'users.role' }
       Article:
            class: App\Entity\Article
            list:
              fields:
                - id
                - { property: 'title', label: 'article.title' }
                - { property: 'content', label: 'article.content' }
            new:
              fields:
                - '-id'
                - { property: 'title', label: 'article.title' }
                - { property: 'content', type: 'textarea', label: 'article.content' }
            edit:
              fields:
                - { property: 'title', label: 'article.title' }
                - { property: 'content', type: 'textarea', label: 'article.content' }

       Comments:
            class: App\Entity\Comments
            list:
              fields:
                - { property: 'id', label: 'comments.id' }
                - { property: 'content', label: 'comments.content' }
                - { property: 'article_id', label: 'comments.article_id' }
       Birds:
            class: App\Entity\Birds
framework:
  translator: { fallbacks: [ "fr" ] }