security:
    providers:
        in_memory:
          memory:
            users:
              ryan:
                password: ryanpass
                roles: 'ROLE_USER'
              admin:
                password: kitten
                roles: 'ROLE_ADMIN'
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      App\Entity\Users:
        algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~


    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }