easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation
    # entities:
    #     - App\Entity\Comments
    #     - App\Entity\Article
    #     - App\Entity\Users